### ISSUE TITLE
Allow for dynamic updates of email authorization file

### ISSUE THREAD

**Issue by razb** [bitly/google_auth_proxy#41]
Currently, it looks like the email file is only read at startup. It would be useful to allow this to be read at login so users could be added/deleted dynamically.

**Comment by mbland** [comment]
Yes, I was wondering if it was by design that a restart is required. However, searching around just now, it seems there isn't yet a standard file watching API. Now that https://github.com/go-fsnotify/fsnotify appears poised to go into the standard library, perhaps we could give that a spin? Happy to whip up a PR for this if no one else gets to it first.

**Comment by jehiah** [comment]
Yeah, `fsnotify` would be a good approach to solving this. I'm not sure what that means for windows support, but i'm sure if needed that could be omitted via build tags.
