### ISSUE TITLE
Google auth requires offline access acceptance

### ISSUE THREAD

**Issue by ianneub** [bitly/google_auth_proxy#96]
I see this message all the time while trying to login using google oauth:

![Image of offline access](http://ianneubert.com/temp/skitch/Request_for_Permission_1B07AA64.png)

```
<Application> would like to:

* Have offline access
```

Is it possible to get rid of this message?

I am using the following settings:
`-authenticated-emails-file=/emails.txt -upstream="http://web:3000/" -cookie-secret="asdf" -http-address=0.0.0.0:80 -cookie-expire=8h0m0s`

Thanks!

**Comment by jehiah** [comment]
@ianneub no. "offline access" just means the proxy app gets a token that can be used. The only permission requested is to query email address, so that's the only thing the token is good for. 

The need for a token that can be used "offline" is to re-validate a session later separate from when a cookie expires as recently happened in #88.

Let me know if that helps or if there are any follow up questions i can answer.
